print("wat is je naam?:")
naam=input()
print("wat is je adress?: ")
adres= input()
print("wat is je postcode?: ")
postcode= input()
print("wat is je woonplaats?: ")
woonplaats=input()
print("naam: ", naam)
print("adres: ",adres)
print("postcode: ", postcode)
print("woonplaats: ", woonplaats)
